# Generated by Django 4.2.30 on 2026-04-24 05:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, related_name='usuario_cine_set', to='auth.group', verbose_name='Grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='usuario_cine_set', to='auth.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['nombre_completo'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'genero',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la sala')),
                ('capacidad_maxima', models.PositiveIntegerField(verbose_name='Capacidad máxima')),
                ('layout_config', models.JSONField(blank=True, null=True, verbose_name='Configuración del layout')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('mantenimiento', 'En mantenimiento')], default='activa', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'sala',
                'ordering': ['nombre_sala'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('clasificacion', models.CharField(choices=[('ATP', 'Apta para Todo Público'), ('+13', 'Mayores de 13 años'), ('+16', 'Mayores de 16 años'), ('+18', 'Mayores de 18 años')], max_length=3, verbose_name='Clasificación')),
                ('es_clasica', models.BooleanField(default=False, verbose_name='¿Es clásica?')),
                ('imagen_poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Póster')),
                ('generos', models.ManyToManyField(related_name='peliculas', to='sistema_cine.genero', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'db_table': 'pelicula',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Empleado')),
                ('id_validador', models.CharField(max_length=50, unique=True, verbose_name='ID de validador')),
                ('terminal_venta', models.PositiveIntegerField(verbose_name='Terminal de venta')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Administrador')),
                ('nivel_gestion', models.CharField(max_length=50, verbose_name='Nivel de gestión')),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de entrada')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='sistema_cine.pelicula', verbose_name='Película')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='sistema_cine.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'funcion',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('sala', 'fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=5, verbose_name='Fila')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('tipo_asiento', models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('discapacitado', 'Discapacitado')], default='general', max_length=15, verbose_name='Tipo de asiento')),
                ('posicion_x', models.PositiveIntegerField(verbose_name='Posición X')),
                ('posicion_y', models.PositiveIntegerField(verbose_name='Posición Y')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='sistema_cine.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'db_table': 'asiento',
                'ordering': ['sala', 'fila', 'numero'],
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
