# Generated by Django 4.2.30 on 2026-04-23 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'db_table': 'genero',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sala', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la sala')),
                ('capacidad_maxima', models.PositiveIntegerField(verbose_name='Capacidad máxima')),
                ('layout_config', models.JSONField(blank=True, null=True, verbose_name='Configuración del layout')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('mantenimiento', 'En mantenimiento')], default='activa', max_length=15, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'sala',
                'ordering': ['nombre_sala'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('duracion_minutos', models.PositiveIntegerField(verbose_name='Duración (minutos)')),
                ('clasificacion', models.CharField(choices=[('ATP', 'Apta para Todo Público'), ('+13', 'Mayores de 13 años'), ('+16', 'Mayores de 16 años'), ('+18', 'Mayores de 18 años')], max_length=3, verbose_name='Clasificación')),
                ('es_clasica', models.BooleanField(default=False, verbose_name='¿Es clásica?')),
                ('imagen_poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Póster')),
                ('generos', models.ManyToManyField(related_name='peliculas', to='sistema_cine.genero', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'db_table': 'pelicula',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio de entrada')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='sistema_cine.pelicula', verbose_name='Película')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='sistema_cine.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'funcion',
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('sala', 'fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=5, verbose_name='Fila')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('tipo_asiento', models.CharField(choices=[('general', 'General'), ('vip', 'VIP'), ('discapacitado', 'Discapacitado')], default='general', max_length=15, verbose_name='Tipo de asiento')),
                ('posicion_x', models.PositiveIntegerField(verbose_name='Posición X')),
                ('posicion_y', models.PositiveIntegerField(verbose_name='Posición Y')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='sistema_cine.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Asiento',
                'verbose_name_plural': 'Asientos',
                'db_table': 'asiento',
                'ordering': ['sala', 'fila', 'numero'],
                'unique_together': {('sala', 'fila', 'numero')},
            },
        ),
    ]
