# Generated by Django 4.2.30 on 2026-05-18 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='estado',
            field=models.CharField(choices=[('cartelera', 'En cartelera'), ('proximamente', 'Próximamente'), ('retirada', 'Retirada')], default='proximamente', max_length=15, verbose_name='Estado en cartelera'),
        ),
    ]
