# Generated by Django 4.2.30 on 2026-05-25 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_transaccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('tarjeta', 'Tarjeta de Crédito/Débito')], max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-fecha_hora_transaccion'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_qr', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('estado_uso', models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validado', 'Ingreso Validado')], default='pendiente', max_length=20)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_asociados', to='sistema_cine.asiento')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_vendidos', to='sistema_cine.funcion')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='sistema_cine.venta')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'ticket',
                'unique_together': {('funcion', 'asiento')},
            },
        ),
    ]
