# Generated by Django 4.2.30 on 2026-05-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0002_pelicula_estado'),
        ('sistema_cine', '0002_venta_ticket'),
    ]

    operations = [
    ]
