# Generated by Django 4.2.30 on 2026-05-31 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0002_pelicula_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la encuesta')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('fecha_evento', models.DateField(verbose_name='Fecha del evento especial')),
                ('fecha_inicio', models.DateTimeField(verbose_name='Inicio de la votación')),
                ('fecha_fin', models.DateTimeField(verbose_name='Cierre de la votación')),
                ('esta_activa', models.BooleanField(default=True, verbose_name='¿Está activa?')),
                ('peliculas', models.ManyToManyField(limit_choices_to={'es_clasica': True}, related_name='encuestas', to='sistema_cine.pelicula', verbose_name='Películas candidatas')),
            ],
            options={
                'verbose_name': 'Encuesta de votación',
                'verbose_name_plural': 'Encuestas de votación',
                'db_table': 'encuesta',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_voto', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del voto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='sistema_cine.cliente', verbose_name='Cliente')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='sistema_cine.encuesta', verbose_name='Encuesta')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to='sistema_cine.pelicula', verbose_name='Película votada')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'db_table': 'voto',
                'ordering': ['-fecha_voto'],
                'unique_together': {('cliente', 'encuesta')},
            },
        ),
    ]
