# Generated by Django 4.2.30 on 2026-05-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0003_merge_0002_pelicula_estado_0002_venta_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='imagen_qr',
            field=models.ImageField(blank=True, null=True, upload_to='tickets_qr/'),
        ),
    ]
