# Generated by Django 4.2.30 on 2026-05-31 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0003_encuesta_voto'),
        ('sistema_cine', '0004_agregar_imagen_qr_ticket'),
    ]

    operations = [
    ]
