# Generated by Django 4.2.30 on 2026-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0006_triggers_y_procedimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de validación'),
        ),
    ]
