# Generated by Django 4.2.30 on 2026-06-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_cine', '0007_agregar_fecha_validacion_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='estado_asiento',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=15, verbose_name='Estado'),
        ),
    ]
